# -*- coding: utf-8 -*-
from nbsgp import (
    ModuleDefinitionBase,
    ModuleDefinition,
    ProjectDefinitionBase,
    ProjectDefinition,
    ExternalModuleDefinitionBase,
    ExternalModuleDefinition,
    ExternalProjectDefinitionBase,
    ExternalProjectDefinition,
    ModuleDependencyBase,
    ModuleDependency,
    ProjectDependencyBase,
    ProjectDependency,
    ExternalModuleDependencyBase,
    ExternalModuleDependency,
    ExternalProjectDependencyBase,
    ExternalProjectDependency,
    load_extronal_module,
    load_extronal_project,
    load_module,
    load_project,
    MakefileGeneratorBase,
)